# Generated by Django 2.1.3 on 2019-04-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190405_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdffile',
            field=models.FileField(upload_to=''),
        ),
    ]
